const post = [
  {
    id: 1,
    title: "Buying new player",
    sport: "Football",
    author: "Seun tope",
    date: new Date().toISOString(),
    authImg: "img/default.jpg",
    image: "/img/player1.webp",
  },
  {
    id: 2,
    title: "Changing team striker next match ",
    sport: "Football",
    author: "Olamide Olu",
    date: new Date().toISOString(),
    authImg: "img/default.jpg",
    image: "/img/player2.webp",
  },
  {
    id: 3,
    title: "Leaving Chelsea",
    sport: "Football",
    author: "Joseph Goddy",
    date: new Date().toISOString(),
    authImg: "img/default.jpg",
    image: "/img/player3.webp",
  },
  {
    id: 4,
    title: "Signing new goal keeper",
    sport: "Football",
    author: "Jame vin",
    date: new Date().toISOString(),
    authImg: "img/default.jpg",
    image: "/img/player4.jpg",
  },
  {
    id: 5,
    title: "We are not complete to play",
    sport: "Football",
    author: "Emmanuel Lucas",
    date: new Date().toISOString(),
    authImg: "img/default.jpg",
    image: "/img/banner.jpg",
  },
  {
    id: 6,
    title: "We are not complete to play",
    sport: "Football",
    author: "Joyous Kenny",
    date: new Date().toISOString(),
    authImg: "img/default.jpg",
    image: "/img/player5.jpg",
  },
];

export default post;
